# Site settings
title: Ket Labs
email: ssamsonau@ket-labs.com
description: > # this means to ignore newlines until "baseurl:"
 “My dear, here we must run as fast as we can, just to stay in place. And if you wish to go anywhere you must run twice as fast as that.” ― Lewis Carroll, Alice in Wonderland
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.ket-labs.com" # the base hostname & protocol for your site
twitter_username:
github_username:  


# Build settings
markdown: kramdown

# Other options
permalink: /ignited_projects/:year/:month/:title
#job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""